services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - ${NEXTCLOUD_DB_PATH}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: postgres -c 'max_connections=200' -c 'shared_buffers=256MB' -c 'work_mem=16MB' -c 'maintenance_work_mem=256MB' -c 'effective_cache_size=768MB'
    networks:
      - nextcloud_internal

  redis:
    image: redis:alpine
    restart: always
    command: >
      --maxmemory 1024mb 
      --maxmemory-policy volatile-lru 
      --appendonly yes 
      --appendfsync everysec 
      --save 900 1 
      --save 300 10 
      --save 60 10000
    volumes:
      - ./redis_data:/data
    networks:
      - nextcloud_internal

  app:
    image: nextcloud:apache
    restart: always
    ports:
      - "${NEXTCLOUD_PORT}:80"
    volumes:
      - ./nextcloud_data:/var/www/html
      - ./data:/data
      - ./backups:/backups
      - ./nextcloud_data/custom_php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ./apache-config/apache-limits.conf:/etc/apache2/conf-enabled/apache-limits.conf:ro
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - REDIS_HOST=${REDIS_HOST}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
      - PHP_UPLOAD_LIMIT=${PHP_UPLOAD_LIMIT}
      - PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME}
      - PHP_MAX_INPUT_TIME=${PHP_MAX_INPUT_TIME}
      - APACHE_BODY_LIMIT=${APACHE_BODY_LIMIT}
    depends_on:
      - db
      - redis
    networks:
      - nextcloud_internal

networks:
  nextcloud_internal:
    driver: bridge

volumes:
  nextcloud-data: {}
