<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'redis',
    'password' => '',
    'port' => 6379,
  ),
  'upgrade.disable-web' => true,
  'passwordsalt' => 'your_password_salt_here',
  'secret' => 'your_secret_key_here',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'your.domain.com',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'pgsql',
  'version' => '30.0.1.2',
  'overwrite.cli.url' => 'https://your.domain.com',
  'dbname' => 'nextcloud',
  'dbhost' => 'db',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => 'your_database_password_here',
  'installed' => true,
  'instanceid' => 'oc_instance_id',
  'default_phone_region' => 'US',
  'maintenance_window_start' => 1,
  'allow_frame_loading' => true,
  'overwriteprotocol' => 'https',
  'overwritehost' => 'your.domain.com',
  'overwritehost' => 'your.domain.com',
  'overwritecondaddr' => '^192\\.168\\.50\\.',
  'trusted_proxies' => 
  array (
    0 => 'LAN_IP',
    1 => 'LAN_IP',
  ),
  'forwarded_for_headers' => 
  array (
    0 => 'HTTP_X_FORWARDED_FOR',
  ),
  'frame_ancestors' => '\'self\' https://my.domain.com http://lan_ip:port https://*.domain.com',
  'app_install_overwrite' => 
  array (
    0 => 'files_external_gdrive',
    1 => 'transfer',
    2 => 'transmission',
    3 => 'rocketchat_nextcloud',
  ),
  'tempdirectory' => '/var/www/html/data/tmp',
  'maintenance' => false,
  'mail_from_address' => 'your_email',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => 'your_mail_domain',
  'mail_smtphost' => 'smtp.your_provider.com',
  'mail_smtpport' => '587',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'your_email@domain.com',
  'mail_smtppassword' => 'your_smtp_password',
  'max_chunk_size' => 104857600,
  'upload_max_filesize' => '16G',
  'memory_limit' => '4096M',
  'post_max_size' => '16G',
  'max_input_time' => 3600,
  'max_execution_time' => 3600,
  'output_buffering' => 0,
  'memcache.local.cache.enabled' => true,
  'memcache.local.cache.maxsize' => 512,
  'filelocking.enabled' => true,
  'enable_previews' => true,
  'preview_max_filesize_image' => '100M',
  'preview_max_memory' => 256,
  'filesystem_check_changes' => 1,
  'skeletondirectory' => '',
  'versions_retention_obligation' => 'auto,30',
  'auth.bruteforce.protection.enabled' => true,
  'security.strict_auth' => true,
  'security.csp.enabled' => true,
  'redis.allow-unsafe-locking' => false,
  'session_handler' => '\\OC\\Session\\Redis',
  'session_lifetime' => 1440,
  'session.save_handler' => 'redis',
  'session.save_path' => 'tcp://redis:6379',
  'redis.session' => 
  array (
    'locking_enabled' => true,
    'lock_wait_time' => 10000,
    'lock_retry_count' => 10,
  ),
  'cache_path' => '/var/www/html/data/cache',
  'cache_chunk_gc_ttl' => 86400,
  'filesystem_cache_readonly' => false,
  'filesystem_cache_ttl' => 60,
  'part_file_in_storage' => true,
  'mount_file_scan_async' => true,
  'files_no_background_scan' => true,
  'files_max_concurrent_transfers' => 20,
  'dbtype.concurrent_connections' => true,
  'mysql.utf8mb4' => true,
  'log_type' => 'file',
  'logfile' => '/var/www/html/data/nextcloud.log',
  'loglevel' => 2,
  'log_rotate_size' => 104857600,
);
